Transform: AWS::Serverless-2016-10-31

Resources:
  ImageBase:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: base
      ImageTagMutability: MUTABLE

  LayerLambda:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/lambda

  ParameterLayerArnLambda:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /alexandria/layer/sam/lambda
      Value: !Ref LayerFeedparser

Outputs:
  ParameterNameLayerArnLambda:
    Value: !Ref ParameterLayerArnLambda

  UriEcrRepositoryBs4:
    Value: !GetAtt BaseImageBs4.RepositoryUri
