Transform: AWS::Serverless-2016-10-31

Resources:
  BaseImageBs4:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bs4
      ImageTagMutability: MUTABLE

  LayerFeedparser:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/feedparser

  ParameterLayerArnFeedparser:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /alexandria/layer/sam/feedparser
      Value: !Ref LayerFeedparser

Outputs:
  ParameterNameLayerArnFeedparser:
    Value: !Ref ParameterLayerArnFeedparser

  UriEcrRepositoryBs4:
    Value: !GetAtt BaseImageBs4.RepositoryUri
