Transform: AWS::Serverless-2016-10-31

Resources:
  ImageBase:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: base
      ImageTagMutability: MUTABLE

  LayerBase:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/base

  ParameterLayerArnBase:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /alexandria/layer/sam/base
      Value: !Ref LayerBase

Outputs:
  ParameterNameLayerArnLambda:
    Value: !Ref ParameterLayerArnBase

  UriEcrRepositoryBs4:
    Value: !GetAtt ImageBase.RepositoryUri
